# Generated by Django 4.0.5 on 2022-08-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='importance',
            new_name='important',
        ),
    ]
